project:
    type: website
    output-dir: docs

website:
    title: "CPM-SO 2026"
    description: "Research symposium website"
    navbar: 
        left:
            - href: index.qmd
              text: "Home"
            - href: program.qmd
              text: "Program"
            - href: venue.qmd
              text: "Venue"
            - href: register.qmd
              text: "Registration"
            - href: funding.qmd
              text: "Funding"
        right:
        - text: "Register here!"
          href: "https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=PUrf3MDQY0qUz3gZgSSb5TSsRhgHAaxEneI2iwjKTvdUMzI4SDBQTTREVkgyT0tBQzRHUUlEQUM3Ni4u" # Replace with your actual form URL

format:
    html:
        theme: cosmo
        toc: true
        toc-depth: 3